### ISSUE TITLE
is compiler needed for windows?

### ISSUE THREAD

**Issue by mzaiss** [KerstinHut/pypulseq-cest#10]
Hi Kerstin,

I am about to try the python version finally, but dont have a compiler.
Is this actually necessary for windows as maybe precompiled binaries would also work.
Just wondering if we could include them.
Cheers.

**Comment by mzaiss** [comment]
seems to work now.
Is swig needed for this? it seems to me that it was never used then.
then we can maybe remove it from the prerequisites for the precompiled version.

**Comment by KerstinHut** [comment]
The problem is that the precompiled version is strongly system-dependent and I have not yet found a working solution to make it less so. I will work on another installation with @schuenke. Until we have one, Iwill emphasize the existence of the installation files before the description of the system-independent installation in the readme.
